version: "3.8"
services:

  app:
   build:
    context: .
    dockerfile: Dockerfile
   ports:
   - 5000:5000
   volumes:
   - ./app/:/app/
   command: ['python3', 'app.py']
  
  db:
    image: library/postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgreql/data/
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
    